//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokéDex
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokemon
    {
        public int PokemonID { get; set; }
        public int TeamID { get; set; }
        public string PokemonName { get; set; }
        public string move1 { get; set; }
        public string move2 { get; set; }
        public string move3 { get; set; }
        public string move4 { get; set; }
        public int PokemonID { get; set; }
        public int TeamID { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
