//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokéDex
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokemon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pokemon()
        {
            this.PokemonTeams = new HashSet<PokemonTeam>();
        }
    
        public string PokemonName { get; set; }
        public string move1 { get; set; }
        public string move2 { get; set; }
        public string move3 { get; set; }
        public string move4 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PokemonTeam> PokemonTeams { get; set; }
    }
}
